export const GET_WEATHER = 'GET_WEATHER'
export const SET_WEATHER = 'SET_WEATHER'
export const SET_WEATHER_LOADING = 'SET_WEATHER_LOADING'
export const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR'

export const GET_SELECT = 'GET_SELECT'
export const SET_SELECT = 'SET_SELECT'